main: me.zodiia.api.ApiPlugin
version: ${project.version}
name: ${project.name}
api-version: ${minecraft.apiVersion}
author: Zodiia
load: STARTUP
softdepend:
  - Vault
  - PlaceholderAPI
description: ${project.description}
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlin.version}"
  - "org.jetbrains.kotlin:kotlin-reflect:${kotlin.version}"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:${serialization.version}"
  - "com.charleskorn.kaml:kaml:${serialization.kaml.version}"
  - "com.h2database:h2:${h2.version}"
  - "mysql:mysql-connector-java:${mysql-jdbc.version}"
  - "org.mariadb.jdbc:mariadb-java-client:${mariadb-jdbc.version}"
  - "org.postgresql:postgresql:${postgresql-jdbc.version}"
  - "org.jetbrains.exposed:exposed-core:${exposed.version}"
  - "org.jetbrains.exposed:exposed-jdbc:${exposed.version}"
  - "org.jetbrains.exposed:exposed-dao:${exposed.version}"
  - "com.zaxxer:HikariCP:${hikaricp.version}"
