main: me.zodiia.api.ApiPlugin
version: ${project.version}
name: ${project.name}
api-version: ${minecraft.apiVersion}
author: Zodiia
load: STARTUP
softdepend:
  - Vault
  - PlaceholderAPI
description: ${project.description}
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${versions.kotlin}"
  - "org.jetbrains.kotlin:kotlin-reflect:${versions.kotlin}"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:${versions.coroutines}"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-reactor:${versions.coroutines}"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-reactive:${versions.coroutines}"
  - "org.jetbrains.exposed:exposed-core:${versions.exposed}"
  - "org.jetbrains.exposed:exposed-jdbc:${versions.exposed}"
  - "org.jetbrains.exposed:exposed-dao:${versions.exposed}"
  - "com.uchuhimo:konf-core:${versions.konf}"
  - "com.uchuhimo:konf-yaml:${versions.konf}"
  - "com.uchuhimo:konf-hocon:${versions.konf}"
  - "com.vdurmont:semver4j:${versions.semver4j}"
  - "io.projectreactor:reactor-core:${versions.reactor-core}"
  - "io.projectreactor.netty:reactor-netty:${versions.reactor-netty}"
  - "com.h2database:h2:${versions.h2}"
  - "mysql:mysql-connector-java:${versions.mysql-jdbc}"
  - "org.mariadb.jdbc:mariadb-java-client:${versions.mariadb-jdbc}"
  - "org.postgresql:postgresql:${versions.postgresql-jdbc}"
  - "com.zaxxer:HikariCP:${versions.hikaricp}"
